CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    fullname TEXT NOT NULL,
    login TEXT NOT NULL UNIQUE,
    salt CHAR(32) NOT NULL,
    password_sha_256 CHAR(64) NOT NULL
);

CREATE TABLE IF NOT EXISTS characters (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id),
    name TEXT NOT NULL,
    data JSONB
);